### ISSUE TITLE
generate fr and de - 778

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/storagegrid-enable#14]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-gudugunti** [comment]
PDFs are not available (including on us-en).
Site is up and running.
BPR and labels are set.

**Comment by netapp-gudugunti** [comment]
> @netapp-gudugunti - This is tagged to Danielle or me, but i'm not sure what you need us to do.

@ntap-bmegan Just wanted to confirm whether it is fine with not providing PDF format? 
![image](https://user-images.githubusercontent.com/86427254/202485654-7c830bd2-9171-49c8-a4e0-846debe8b327.png)
If yes, I shall go ahead and close this ticket.

**Comment by ntap-bmegan** [comment]
It's not related to the French & German work, so close.
