### ISSUE TITLE
Typo in loadbalancer section

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/storagegrid-enable#48]
### Page URL

https://docs.netapp.com/us-en/storagegrid-enable/tools-apps-guides/veeam-br.html

### Page title

StorageGRID best practices for deployment with Veeam Backup and Replication

### Summary

"Loadbalanacer.org" - should be "loadbalancer.org"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aronk** [comment]
corrected thanks.
