### ISSUE TITLE
Data Tiering listed as a use case twice

### ISSUE THREAD

**Issue by cecilekNetApp** [NetAppDocs/storagegrid-enable#69]
### Page URL

https://docs.netapp.com/us-en/storagegrid-enable/technical-reports/datalake-analytics.html

### Page title

NetApp StorageGRID and big data analytics

### Summary

Data Tiering is listed as the 2nd and 6th use case (duplicatation)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aronk** [comment]
fixed.
